### ISSUE TITLE
[Fabric] Crash on server start

### ISSUE THREAD

**Issue by Koronos** [Spottedleaf/Starlight#106]
I have a server running in 1.18, but when it starts crashes immediately. Is the unique mod in the server.

MC Version: 1.18
Java: OpenJDK 17.0.1 64-bits
Fabric loader: 0.12.9
Fabric Api: 0.44.0+1.18
startlight: 1.0.0+fabric.d0a3220

Here's the log:
```
[18:53:45] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/home/container/versions/118fabric/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[18:53:45] [main/INFO]: Compatibility level set to JAVA_16
[18:53:45] [main/ERROR]: Uncaught exception in thread "main"
java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:68) ~[fabric-server-launch.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) ~[fabric-server-launch.jar:?]
Caused by: java.lang.RuntimeException: Error creating Mixin config starlight.mixins.json for mod starlight
        at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:90) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) ~[fabric-server-launch.jar:?]
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config starlight.mixins.json
        at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) ~[fabric-server-launch.jar:?]
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.0 (ASM10_EXPERIMENTAL))
        at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1570) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) ~[fabric-server-launch.jar:?]
```

**Comment by Chew** [comment]
Unable to reproduce, please ensure you're using the right version of Starlight and Java 17 (check with `java -version`)

1.18 Starlight: https://cdn.modrinth.com/data/H8CaAYZC/versions/Starlight%201.0.0%201.18.x/starlight-1.0.0+fabric.d0a3220.jar

```
% java -jar fabric-server-launch.jar
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[19:44:34] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.18 with Fabric Loader 0.12.9
[19:44:34] [main/INFO]: Loading Minecraft 1.18 with Fabric Loader 0.12.9
[19:44:34] [main/WARN]: Warnings were found!
 - Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d95c8 recommends any version of fabric-textures-v0, which is disabled for this environment (client/server only)!
	 - You should install any version of fabric-textures-v0 for the optimal experience.
[19:44:34] [main/INFO]: Loading 38 mods:
	- fabric 0.44.0+1.18
	- fabric-api-base 0.4.1+b4f4f6cdc8 via fabric
	- fabric-api-lookup-api-v1 1.4.0+16d92c47c8 via fabric
	- fabric-biome-api-v1 6.0.1+ded849a9c8 via fabric
	- fabric-command-api-v1 1.1.6+3ac43d95c8 via fabric
	- fabric-commands-v0 0.2.5+b4f4f6cdc8 via fabric
	- fabric-containers-v0 0.1.18+d154e2c6c8 via fabric
	- fabric-content-registries-v0 0.4.5+6f53a73dc8 via fabric
	- fabric-crash-report-info-v1 0.1.8+3ac43d95c8 via fabric
	- fabric-dimensions-v1 2.1.7+43d29571c8 via fabric
	- fabric-entity-events-v1 1.4.5+6b21378ac8 via fabric
	- fabric-events-interaction-v0 0.4.16+bfa23f17c8 via fabric
	- fabric-events-lifecycle-v0 0.2.6+b4f4f6cdc8 via fabric
	- fabric-game-rule-api-v1 1.0.10+3ac43d95c8 via fabric
	- fabric-item-api-v1 1.3.0+691a79b5c8 via fabric
	- fabric-item-groups-v0 0.3.3+3ac43d95c8 via fabric
	- fabric-lifecycle-events-v1 1.4.10+c15ca335c8 via fabric
	- fabric-loot-tables-v1 1.0.8+3ac43d95c8 via fabric
	- fabric-mining-level-api-v1 1.0.3+3ac43d95c8 via fabric
	- fabric-mining-levels-v0 0.1.7+b4f4f6cdc8 via fabric
	- fabric-networking-api-v1 1.0.18+3ac43d95c8 via fabric
	- fabric-networking-v0 0.3.5+b4f4f6cdc8 via fabric
	- fabric-object-builder-api-v1 1.11.0+3b82842ec8 via fabric
	- fabric-object-builders-v0 0.7.8+3ac43d95c8 via fabric
	- fabric-particles-v1 0.2.9+526dc1acc8 via fabric
	- fabric-registry-sync-v0 0.8.5+3ac43d95c8 via fabric
	- fabric-rendering-data-attachment-v1 0.3.4+7242e9d7c8 via fabric
	- fabric-rendering-fluids-v1 0.1.18+3ac43d95c8 via fabric
	- fabric-resource-loader-v0 0.4.11+3ac43d95c8 via fabric
	- fabric-screen-handler-api-v1 1.1.11+3ac43d95c8 via fabric
	- fabric-structure-api-v1 2.0.8+295197a7c8 via fabric
	- fabric-tag-extensions-v0 1.2.5+3ac43d95c8 via fabric
	- fabric-tool-attribute-api-v1 1.3.4+7de09f55c8 via fabric
	- fabric-transfer-api-v1 1.5.5+b4f4f6cdc8 via fabric
	- fabricloader 0.12.9
	- java 17
	- minecraft 1.18
	- starlight 1.0.0+fabric.d0a3220
[19:44:34] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/Users/chew/Downloads/fab/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=SERVER
[19:44:34] [main/INFO]: Compatibility level set to JAVA_16
[19:44:34] [main/INFO]: Compatibility level set to JAVA_17
[19:44:36] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:server.WorldChunkMixin::handler$zca000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[19:44:38] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19:44:38] [main/INFO]: Found new data pack Fabric Mods, loading it automatically
[19:44:39] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[19:44:39] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[19:44:39] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[19:44:39] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[19:44:39] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[19:44:39] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Tool Attribute API (v1))
[19:44:39] [Worker-Main-12/INFO]: Loaded 7 recipes
[19:44:39] [Worker-Main-12/INFO]: Loaded 1141 advancements
[19:44:40] [main/INFO]: Applied 0 biome modifications to 0 of 61 new biomes in 3.551 ms
[19:44:42] [main/INFO]: [STDERR]: Warning: the fonts "Times" and "Times" are not available for the Java logical font "Serif", which may have unexpected appearance or behavior. Re-enable the "Times" font to remove this warning.
[19:44:43] [Server thread/INFO]: Starting minecraft server version 1.18
[19:44:43] [Server thread/INFO]: Loading properties
[19:44:43] [Server thread/INFO]: Default game type: SURVIVAL
[19:44:43] [Server thread/INFO]: Generating keypair
[19:44:43] [Server thread/INFO]: Starting Minecraft server on *:25565
[19:44:43] [Server thread/INFO]: Using default channel type
[19:44:43] [Server thread/INFO]: Preparing level "world"
[19:44:48] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[19:44:49] [Worker-Main-14/INFO]: Preparing spawn area: 0%
[19:44:49] [Worker-Main-9/INFO]: Preparing spawn area: 0%
[19:44:49] [Worker-Main-9/INFO]: Preparing spawn area: 0%
[19:44:50] [Worker-Main-14/INFO]: Preparing spawn area: 0%
[19:44:50] [Worker-Main-8/INFO]: Preparing spawn area: 0%
[19:44:51] [Worker-Main-9/INFO]: Preparing spawn area: 1%
[19:44:51] [Worker-Main-14/INFO]: Preparing spawn area: 2%
[19:44:52] [Worker-Main-11/INFO]: Preparing spawn area: 3%
[19:44:52] [Worker-Main-9/INFO]: Preparing spawn area: 4%
[19:44:53] [Worker-Main-10/INFO]: Preparing spawn area: 5%
[19:44:53] [Worker-Main-14/INFO]: Preparing spawn area: 6%
[19:44:54] [Worker-Main-10/INFO]: Preparing spawn area: 8%
[19:44:54] [Worker-Main-8/INFO]: Preparing spawn area: 10%
[19:44:55] [Worker-Main-10/INFO]: Preparing spawn area: 13%
[19:44:56] [Worker-Main-9/INFO]: Preparing spawn area: 15%
[19:44:56] [Worker-Main-8/INFO]: Preparing spawn area: 15%
[19:44:56] [Worker-Main-10/INFO]: Preparing spawn area: 15%
[19:44:57] [Worker-Main-9/INFO]: Preparing spawn area: 17%
[19:44:57] [Worker-Main-14/INFO]: Preparing spawn area: 18%
[19:44:58] [Worker-Main-10/INFO]: Preparing spawn area: 20%
[19:44:58] [Worker-Main-12/INFO]: Preparing spawn area: 21%
[19:44:59] [Worker-Main-14/INFO]: Preparing spawn area: 23%
[19:44:59] [Worker-Main-8/INFO]: Preparing spawn area: 26%
[19:45:00] [Worker-Main-10/INFO]: Preparing spawn area: 28%
[19:45:00] [Worker-Main-9/INFO]: Preparing spawn area: 29%
[19:45:01] [Worker-Main-11/INFO]: Preparing spawn area: 31%
[19:45:01] [Worker-Main-8/INFO]: Preparing spawn area: 32%
[19:45:02] [Worker-Main-8/INFO]: Preparing spawn area: 35%
[19:45:02] [Worker-Main-9/INFO]: Preparing spawn area: 37%
[19:45:03] [Worker-Main-12/INFO]: Preparing spawn area: 40%
[19:45:03] [Worker-Main-14/INFO]: Preparing spawn area: 42%
[19:45:04] [Worker-Main-9/INFO]: Preparing spawn area: 44%
[19:45:04] [Worker-Main-9/INFO]: Preparing spawn area: 48%
[19:45:05] [Worker-Main-9/INFO]: Preparing spawn area: 48%
[19:45:05] [Worker-Main-8/INFO]: Preparing spawn area: 50%
[19:45:06] [Worker-Main-13/INFO]: Preparing spawn area: 52%
[19:45:06] [Worker-Main-10/INFO]: Preparing spawn area: 55%
[19:45:07] [Worker-Main-11/INFO]: Preparing spawn area: 57%
[19:45:07] [Worker-Main-11/INFO]: Preparing spawn area: 58%
[19:45:08] [Worker-Main-11/INFO]: Preparing spawn area: 61%
[19:45:08] [Worker-Main-9/INFO]: Preparing spawn area: 63%
[19:45:09] [Worker-Main-14/INFO]: Preparing spawn area: 67%
[19:45:09] [Worker-Main-11/INFO]: Preparing spawn area: 68%
[19:45:10] [Worker-Main-8/INFO]: Preparing spawn area: 71%
[19:45:11] [Worker-Main-14/INFO]: Preparing spawn area: 71%
[19:45:11] [Worker-Main-14/INFO]: Preparing spawn area: 73%
[19:45:11] [Worker-Main-11/INFO]: Preparing spawn area: 76%
[19:45:12] [Worker-Main-13/INFO]: Preparing spawn area: 79%
[19:45:12] [Worker-Main-9/INFO]: Preparing spawn area: 83%
[19:45:13] [Worker-Main-12/INFO]: Preparing spawn area: 83%
[19:45:13] [Worker-Main-14/INFO]: Preparing spawn area: 85%
[19:45:14] [Worker-Main-11/INFO]: Preparing spawn area: 86%
[19:45:14] [Worker-Main-8/INFO]: Preparing spawn area: 88%
[19:45:15] [Worker-Main-8/INFO]: Preparing spawn area: 89%
[19:45:15] [Worker-Main-14/INFO]: Preparing spawn area: 93%
[19:45:16] [Server thread/INFO]: Time elapsed: 27473 ms
[19:45:16] [Server thread/INFO]: Done (32.738s)! For help, type "help"
```

It would tell you the Java version in the mod list, I guess?

**Comment by AITYunivers** [comment]
I get the same issue here.

**Comment by Spottedleaf** [comment]
Update your server, known problem on older fabric stuff

**Comment by Spottedleaf** [comment]
You also need to update the fabric installer, as that has the actual fix.

**Comment by Koronos** [comment]
Thx, it fixed updating the fabric installer and using the last loader

**Comment by whaxV** [comment]
same for 1.16.5
??
