### ISSUE TITLE
Crash Report.

### ISSUE THREAD

**Issue by ExeelVT** [Spottedleaf/Starlight#112]
We have run into a crash were its seems to not like Create mod. I have tested this twice so far even on a server.
This is a Client side crash. 

Crashlogs:
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 12/25/21, 6:45 PM
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: Index 16 out of bounds for length 16
	at ca.spottedleaf.starlight.common.light.StarLightEngine.setBlocksForChunkInCache(StarLightEngine.java:229) ~[starlight-1.0.0+forge.4fd2e63.jar%2363!:1.0.0+forge.4fd2e63] {re:mixin,re:classloading}
	at ca.spottedleaf.starlight.common.light.StarLightEngine.setupCaches(StarLightEngine.java:203) ~[starlight-1.0.0+forge.4fd2e63.jar%2363!:1.0.0+forge.4fd2e63] {re:mixin,re:classloading}
	at ca.spottedleaf.starlight.common.light.StarLightEngine.blocksChangedInChunk(StarLightEngine.java:415) ~[starlight-1.0.0+forge.4fd2e63.jar%2363!:1.0.0+forge.4fd2e63] {re:mixin,re:classloading}
	at ca.spottedleaf.starlight.common.light.StarLightInterface.propagateChanges(StarLightInterface.java:544) ~[starlight-1.0.0+forge.4fd2e63.jar%2363!:1.0.0+forge.4fd2e63] {re:mixin,re:classloading}
	at net.minecraft.world.level.lighting.LevelLightEngine.m_142528_(LevelLightEngine.java:602) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:starlight.mixins.json:common.lightengine.LevelLightEngineMixin,pl:mixin:A}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.ContraptionRenderDispatcher.setupRenderWorld(ContraptionRenderDispatcher.java:117) ~[create-mc1.18.1_v0.4a.jar%2356!:mc1.18.1_v0.4a] {re:classloading,pl:runtimedistcleaner:A}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.FlwContraptionManager.create(FlwContraptionManager.java:80) ~[create-mc1.18.1_v0.4a.jar%2356!:mc1.18.1_v0.4a] {re:classloading}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.FlwContraptionManager.create(FlwContraptionManager.java:20) ~[create-mc1.18.1_v0.4a.jar%2356!:mc1.18.1_v0.4a] {re:classloading}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.ContraptionRenderManager.getRenderInfo(ContraptionRenderManager.java:94) ~[create-mc1.18.1_v0.4a.jar%2356!:mc1.18.1_v0.4a] {re:classloading}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.ContraptionRenderManager.tick(ContraptionRenderManager.java:67) ~[create-mc1.18.1_v0.4a.jar%2356!:mc1.18.1_v0.4a] {re:classloading}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.FlwContraptionManager.tick(FlwContraptionManager.java:28) ~[create-mc1.18.1_v0.4a.jar%2356!:mc1.18.1_v0.4a] {re:classloading}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.ContraptionRenderDispatcher.tick(ContraptionRenderDispatcher.java:62) ~[create-mc1.18.1_v0.4a.jar%2356!:mc1.18.1_v0.4a] {re:classloading,pl:runtimedistcleaner:A}
	at com.simibubi.create.events.ClientEvents.onTick(ClientEvents.java:143) ~[create-mc1.18.1_v0.4a.jar%2356!:mc1.18.1_v0.4a] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_110_ClientEvents_onTick_ClientTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostClientTick(ForgeEventFactory.java:876) ~[forge-1.18.1-39.0.8-universal.jar%2370!:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1733) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1015) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.8.jar%2323!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at ca.spottedleaf.starlight.common.light.StarLightEngine.setBlocksForChunkInCache(StarLightEngine.java:229) ~[starlight-1.0.0+forge.4fd2e63.jar%2363!:1.0.0+forge.4fd2e63] {re:mixin,re:classloading}
	at ca.spottedleaf.starlight.common.light.StarLightEngine.setupCaches(StarLightEngine.java:203) ~[starlight-1.0.0+forge.4fd2e63.jar%2363!:1.0.0+forge.4fd2e63] {re:mixin,re:classloading}
	at ca.spottedleaf.starlight.common.light.StarLightEngine.blocksChangedInChunk(StarLightEngine.java:415) ~[starlight-1.0.0+forge.4fd2e63.jar%2363!:1.0.0+forge.4fd2e63] {re:mixin,re:classloading}
	at ca.spottedleaf.starlight.common.light.StarLightInterface.propagateChanges(StarLightInterface.java:544) ~[starlight-1.0.0+forge.4fd2e63.jar%2363!:1.0.0+forge.4fd2e63] {re:mixin,re:classloading}
	at net.minecraft.world.level.lighting.LevelLightEngine.m_142528_(LevelLightEngine.java:602) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:starlight.mixins.json:common.lightengine.LevelLightEngineMixin,pl:mixin:A}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.ContraptionRenderDispatcher.setupRenderWorld(ContraptionRenderDispatcher.java:117) ~[create-mc1.18.1_v0.4a.jar%2356!:mc1.18.1_v0.4a] {re:classloading,pl:runtimedistcleaner:A}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.FlwContraptionManager.create(FlwContraptionManager.java:80) ~[create-mc1.18.1_v0.4a.jar%2356!:mc1.18.1_v0.4a] {re:classloading}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.FlwContraptionManager.create(FlwContraptionManager.java:20) ~[create-mc1.18.1_v0.4a.jar%2356!:mc1.18.1_v0.4a] {re:classloading}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.ContraptionRenderManager.getRenderInfo(ContraptionRenderManager.java:94) ~[create-mc1.18.1_v0.4a.jar%2356!:mc1.18.1_v0.4a] {re:classloading}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.ContraptionRenderManager.tick(ContraptionRenderManager.java:67) ~[create-mc1.18.1_v0.4a.jar%2356!:mc1.18.1_v0.4a] {re:classloading}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.FlwContraptionManager.tick(FlwContraptionManager.java:28) ~[create-mc1.18.1_v0.4a.jar%2356!:mc1.18.1_v0.4a] {re:classloading}
	at com.simibubi.create.content.contraptions.components.structureMovement.render.ContraptionRenderDispatcher.tick(ContraptionRenderDispatcher.java:62) ~[create-mc1.18.1_v0.4a.jar%2356!:mc1.18.1_v0.4a] {re:classloading,pl:runtimedistcleaner:A}
	at com.simibubi.create.events.ClientEvents.onTick(ClientEvents.java:143) ~[create-mc1.18.1_v0.4a.jar%2356!:mc1.18.1_v0.4a] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_110_ClientEvents_onTick_ClientTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostClientTick(ForgeEventFactory.java:876) ~[forge-1.18.1-39.0.8-universal.jar%2370!:?] {re:classloading}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['exeel11'/17265, l='ClientLevel', x=-63.79, y=63.69, z=-90.26]]
	Chunk stats: 289, 166
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,72,-80), Section: (at 0,8,0 in 1,4,-5; chunk contains blocks 16,-64,-80 to 31,319,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 729546 game time, 838588 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:517) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:starlight.mixins.json:client.world.ClientLevelMixin,pl:mixin:APP:create.mixins.json:DestroyProgressMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2249) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:682) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%2366!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.8.jar%2323!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2060074016 bytes (1964 MiB) / 3963617280 bytes (3780 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 2700X Eight-Core Processor         
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): 3.69
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 2080 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e81
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9709
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.67
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.67
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 37723.97
	Virtual memory used (MB): 21304.14
	Swap memory total (MB): 5025.53
	Swap memory used (MB): 162.64
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8192m -Xms256m
	Launched Version: forge-39.0.8
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 497.09, NVIDIA Corporation
	Window size: 1920x1061
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 2700X Eight-Core Processor 
	OptiFine Version: OptiFine_1.18.1_HD_U_H4
	OptiFine Build: 20211212-175054
	Render Distance Chunks: 9
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 497.09
	OpenGlRenderer: NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		MouseTweaks-forge-mc1.18-2.21.jar                 |Mouse Tweaks                  |mousetweaks                   |2.21                |DONE      |Manifest: NOSIGNATURE
		BetterCrates-1.18.1-1.0.0.jar                     |Better Crates                 |bettercrates                  |1.0.0               |DONE      |Manifest: NOSIGNATURE
		starlight-1.0.0+forge.4fd2e63.jar                 |Starlight                     |starlight                     |1.0.0+forge.b1f6a10 |DONE      |Manifest: NOSIGNATURE
		jei-1.18.1-9.1.1.48.jar                           |Just Enough Items             |jei                           |9.1.1.48            |DONE      |Manifest: NOSIGNATURE
		maessentials-1.18-3.7.1.jar                       |MaEssentials                  |maessentials                  |1.18-3.7.1          |DONE      |Manifest: NOSIGNATURE
		betterfpsdist-1.18-1.1.jar                        |betterfpsdist mod             |betterfpsdist                 |1.18-1.1            |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.0.8-universal.jar                 |Forge                         |forge                         |39.0.8              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		appleskin-forge-mc1.18-2.2.0.jar                  |AppleSkin                     |appleskin                     |2.2.0               |DONE      |Manifest: NOSIGNATURE
		toms_storage-1.18-1.2.23.jar                      |Tom's Simple Storage Mod      |toms_storage                  |1.2.23              |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18-0.4.2-rc.jar                  |Flywheel                      |flywheel                      |1.18-0.4.2-rc       |DONE      |Manifest: NOSIGNATURE
		create-mc1.18.1_v0.4a.jar                         |Create                        |create                        |0.4a                |DONE      |Manifest: NOSIGNATURE
		Terralith_v2.0.6_Fabric+Forge.jar                 |Seed Fix + Terralith          |seedfix_forge                 |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		Croptopia-1.18-FORGE-1.7.4.jar                    |Croptopia                     |croptopia                     |1.7.4               |DONE      |Manifest: NOSIGNATURE
		journeymap-1.18.1-5.8.0beta4.jar                  |Journeymap                    |journeymap                    |5.8.0beta4          |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 09d5e564-068b-4ffd-b17b-c6d7cd38479c
	FML: 39.0
	Forge: net.minecraftforge:39.0.8

**Comment by e-im** [comment]
Create incompatibility is tracked by #45
