### ISSUE TITLE
Error initialising mixin config

### ISSUE THREAD

**Issue by craftish37** [Spottedleaf/Starlight#113]
Hello, just seen your forge port for starlight, because I already played with starlight on fabric and seen th huge power of this mod, I jsut decided to add it to my _little_ mopack, but I just encounter a crash at starting saying :
```
[18:15:00] [main/WARN]: LEGACY JDK DETECTED, SECURED JAR HANDLING DISABLED
[18:15:00] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[18:15:00] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/HellNoThat'sMyName/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[18:15:02] [main/WARN]: Mod file Mod File: C:\Users\HellNoThat'sMyName\curseforge\minecraft\Instances\ChocoCraft 1.16.5\mods\dashloader-1.3-alpha.jar is missing mods.toml file
[18:15:02] [main/WARN]: File C:\Users\HellNoThat'sMyName\curseforge\minecraft\Instances\ChocoCraft 1.16.5\mods\dashloader-1.3-alpha.jar has been ignored - it is invalid
[18:15:03] [main/INFO]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 13:0 token recognition error at: '`'
[18:15:03] [main/INFO]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:0 token recognition error at: '~'
[18:15:05] [main/ERROR]: Mixin config boss_tools.mixin.json does not specify "minVersion" property
[18:15:05] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config starlight-x-create.mixins.json
[18:15:05] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
[18:15:05] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
[18:15:05] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
[18:15:05] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addConfig(MixinPlatformManager.java:262)
[18:15:05] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformAgentDefault.prepare(MixinPlatformAgentDefault.java:46)
[18:15:05] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinContainer.prepare(MixinContainer.java:122)
[18:15:05] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.createContainerFor(MixinPlatformManager.java:144)
[18:15:05] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addContainer(MixinPlatformManager.java:134)
[18:15:05] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addNestedContainers(MixinPlatformManager.java:152)
[18:15:05] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.scanForContainers(MixinPlatformManager.java:213)
[18:15:05] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:186)
[18:15:05] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
[18:15:05] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:201)
[18:15:05] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:195)
[18:15:05] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
[18:15:05] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler$$Lambda$462/551706599.accept(Unknown Source)
[18:15:05] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap.forEach(HashMap.java:1280)
[18:15:05] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
[18:15:05] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[18:15:05] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[18:15:05] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[18:15:05] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[18:15:05] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.IllegalArgumentException: The specified resource 'starlight-x-create.mixins.json' was invalid or could not be read
[18:15:05] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1282)
[18:15:05] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
[18:15:05] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 21 more
```
Theses are the full logs, hope it'll help to fix that :D

**Comment by jpenilla** [comment]
`starlight-x-create.mixins.json` isn't the name of starlight's mixin json, are you using an unofficial build?

**Comment by craftish37** [comment]
It’s actually the one that is available on curseforge : https://curseforge.com/minecraft/mc-mods/starlight-forge

**Comment by jpenilla** [comment]
does this happen with only starlight and no other mods? that error does not seem to be from starlight.

**Comment by craftish37** [comment]
Well, it appears to be a compat problem, but it works well with about all my mods that affects render
I'll search what is the problematic mod tomorrow, but if you want check my modlist, here's the link :
https://curseforge.com/minecraft/modpacks/chococraft

**Comment by Spottedleaf** [comment]
1.16.5 is not supported
