### ISSUE TITLE
[Fabric 1.18.2] Server throws java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set.

### ISSUE THREAD

**Issue by Vavency** [Spottedleaf/Starlight#141]
Java Version: openjdk 17.0.2 2022-01-18
Minecraft version: 1.18.2
Fabric Version: 0.13.3
Starlight Version: 1.0.2+fabric.89b8d9f

console log:
```openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment 21.9 (build 17.0.2+8)
OpenJDK 64-Bit Server VM 21.9 (build 17.0.2+8, mixed mode, sharing)
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[21:57:01] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[21:57:02] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[21:57:02] [main/INFO]: Loading 4 mods:
        - fabricloader 0.13.3
        - java 17
        - minecraft 1.18.2
        - starlight 1.0.2+fabric.89b8d9f
[21:57:02] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/vavency/Games/ATLauncher/servers/Minecraft1182withFabric/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[21:57:02] [main/ERROR]: Uncaught exception in thread "main"
java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:68) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:25) ~[fabric-server-launch.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) ~[fabric-server-launch.jar:?]
        ... 1 more
Caused by: java.lang.RuntimeException: Error creating Mixin config starlight.mixins.json for mod starlight
        at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:90) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) ~[fabric-server-launch.jar:?]
        ... 1 more
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config starlight.mixins.json
        at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) ~[fabric-server-launch.jar:?]
        ... 1 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.0 (ASM10_EXPERIMENTAL))
        at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1570) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) ~[fabric-server-launch.jar:?]
        ... 1 more
```

**Comment by Spottedleaf** [comment]
I don't think this is an issue these days.
