### ISSUE TITLE
Crash during light propagation

### ISSUE THREAD

**Issue by segabl** [Spottedleaf/Starlight#146]
Occasionally my server will crash during what seems to be light propagation, it seems to happen more frequently when people go to the nether. A bunch of 
> [07:56:46] [Worker-Main-425/FATAL]: Failed to light chunk [121, -104]

messages pop up in the log until ultimately the server crashes with

> [07:56:46] [Server thread/ERROR]: Encountered an unexpected exception
java.util.concurrent.CompletionException: java.lang.ArrayIndexOutOfBoundsException: Index 512 out of bounds for length 500
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at ca.spottedleaf.starlight.common.light.StarLightInterface.propagateChanges(StarLightInterface.java:529) ~[starlight-1.0.0+fabric.d0a3220.jar:?]
	at net.minecraft.class_3568.method_15516(class_3568.java:602) ~[server-intermediary.jar:?]
	at net.minecraft.class_3227.method_14277(class_3227.java:177) ~[server-intermediary.jar:?]
	at net.minecraft.class_3227.method_19505(class_3227.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[server-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[server-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[server-intermediary.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 512 out of bounds for length 500
	at ca.spottedleaf.starlight.common.light.StarLightEngine.getBlockState(StarLightEngine.java:285) ~[starlight-1.0.0+fabric.d0a3220.jar:?]
	at ca.spottedleaf.starlight.common.light.BlockStarLightEngine.lightChunk(BlockStarLightEngine.java:258) ~[starlight-1.0.0+fabric.d0a3220.jar:?]
	at ca.spottedleaf.starlight.common.light.StarLightEngine.light(StarLightEngine.java:907) ~[starlight-1.0.0+fabric.d0a3220.jar:?]
	at ca.spottedleaf.starlight.common.light.StarLightInterface.lightChunk(StarLightInterface.java:430) ~[starlight-1.0.0+fabric.d0a3220.jar:?]
	at net.minecraft.class_3227.md95e86c$lambda$lightChunk$6$2(class_3227.java:697) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 13 more

This happens on fabric for 1.18.1 with around 80 mods, no other mods are touching the light engine as far as I can tell.

**Comment by Spottedleaf** [comment]
If you can produce it on 1.20.2 I can look at this.
