### ISSUE TITLE
tried running better minecraft had just added optifine to it (for shaders) and it gave me an error while it was loading up

### ISSUE THREAD

**Issue by Entity-Error-9558** [Spottedleaf/Starlight#164]
Uncaught exception in thread "main"
java.lang.RuntimeException: Error creating Mixin config fabric-api-lookup-api-v1.mixins.json for mod fabric-api-lookup-api-v1
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:95)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:153)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config fabric-api-lookup-api-v1.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:93)
	... 3 more
Caused by: java.lang.IllegalArgumentException: The specified resource 'fabric-api-lookup-api-v1.mixins.json' was invalid or could not be read
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1290)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 6 more

I didn't mess with anything in the mods, nor did i add any extra mods. I'm not entirely the smartest when it comes to running mods

**Comment by NoahvdAa** [comment]
And the error you got was....?

EDIT: Looking at the description of the modpack, it explicitly tells you that you don't need optifine for shaders
<img width="612" alt="image" src="https://user-images.githubusercontent.com/44026893/196512519-455a0b87-7363-4e8b-ab4b-cb7454bef680.png">

The modpack also appears to be for 1.16.5, which is not a version we support anymore, nor does the pack seem to include starlight by default.

**Comment by chorbintime** [comment]
1) You don't need Optifine for shaders
2) Optifine is extremely incompatible with our modpacks
3) This has literally nothing to do with Starlight

**Comment by NoahvdAa** [comment]
Closing this since the error isn't related to Starlight, as pointed out by chorbintime.
