### ISSUE TITLE
Full CPU usage and then crash.

### ISSUE THREAD

**Issue by K0-RR** [Spottedleaf/Starlight#54]
After loading the world again chunks were not saved, I tried reproducing my steps since this was a fresh world but this time it was running without issues. Probably nothing useful in the logs...

```
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 4/30/21, 11:35 PM
Description: Exception in server tick loop

java.lang.OutOfMemoryError: Java heap space
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.4)
	at ca.spottedleaf.starlight.common.light.SWMRNibbleArray.toVanillaNibble(SWMRNibbleArray.java:363)
	at ca.spottedleaf.starlight.common.light.StarLightInterface$2.getLightSection(StarLightInterface.java:182)
	at net.minecraft.world.ChunkSerializer.serialize(ChunkSerializer:251)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.save(ThreadedAnvilChunkStorage:716)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_20583(ThreadedAnvilChunkStorage:388)
	at net.minecraft.class_3898$$Lambda$9570/0x0000000801b67c40.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.save(ThreadedAnvilChunkStorage:385)
	at net.minecraft.server.world.ServerChunkManager.save(ServerChunkManager:321)
	at net.minecraft.server.world.ServerWorld.save(ServerWorld:710)
	at net.minecraft.server.MinecraftServer.save(MinecraftServer:567)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:83)
	at net.minecraft.server.MinecraftServer.handler$dod000$modifiedRunLoop(MinecraftServer:8310)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:651)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257)
	at net.minecraft.server.MinecraftServer$$Lambda$8351/0x0000000801866c40.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:829)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.8.0-50-generic
	Java Version: 11.0.11, BellSoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), BellSoft
	Memory: 13007968 bytes (12 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 8
	JVM Flags: 2 total; -Xms4096m -Xmx4096m
	Suspected Mods: Starlight (starlight)
	Fabric Mods: 
		advancedchat: AdvancedChat 3.2.0-1.16.5
		alloy_forgery: Alloy Forgery 1.1.0
		amecs: Amecs 1.3.4+mc.1.16.3
		amecsapi: Amecs API 1.1.4+mc1.16.5
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		architectury: Architectury 1.11.144
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autoconfigtoml: AutoConfig-TOML 1.0.0-fabric
		bambootweaks: Bamboo Tweaks 2.0.5
		banner_capes: Banner Capes 0.2.1
		bendy-lib: Bendy api 1.1.0
		bettercaves: YUNG's Better Caves 1.16.5-1.1
		betterend: Better End 0.9.3-pre
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0
		betternether: Better Nether 5.0.7
		biomemakeover: Biome Makeover 1.16.5-1.3.7
		bundlesplus: bundles plus 0.1.8
		byg: BYG 1.1.7
		c2me: Concurrent Chunk Management Engine 0.1-SNAPSHOT
		campanion: Campanion 1.3.5
		cardinal-components-base: Cardinal Components API (base) 2.7.1
		cardinal-components-entity: Cardinal Components API (entities) 2.7.1
		cardinal-components-world: Cardinal Components API (worlds) 2.6.0
		carpet: Carpet Mod 1.4.34
		cavebiomes: Cave Biomes 0.6.2
		charm: Charm 2.3.3-snapshot
		chesttracker: Chest Tracker 0.8.13
		cinderscapes: Cinderscapes 1.3.3
		cloth-api: Cloth API 1.5.50
		cloth-armor-api-v1: Cloth Armor API v1 1.5.50
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.50
		cloth-common-events-v1: Cloth Common Events v1 1.5.50
		cloth-config2: Cloth Config v4 4.11.19
		cloth-datagen-api-v1: Cloth Datagen v1 1.5.50
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.5.50
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.5.50
		cloth-scissors-api-v1: Cloth Scissors API v1 1.5.50
		cloth-utils-v1: Cloth Utils v1 1.5.50
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		consistency_plus: Consistency Plus 0.2.0-beta
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		croptopia: Croptopia 1.3.1
		cullleaves: Cull Leaves 2.1.0
		customportals: Custom Portals 1.3.0
		darkness: True Darkness 1.6.58
		dashloader: DashLoader 1.2-alpha-DevBuild8
		defaultsettings: DefaultSettings 3.0.2
		dehydration: Dehydration 1.1.2
		dynamicsoundfilters: Dynamic Sound Filters 1.2.0+1.16.5
		emotecraft: Emotecraft 2.0.1
		enchant_giver: Enchant Giver 1.0.3
		enhancedblockentities: Enhanced Block Entities 0.1
		entityculling: EntityCulling-Fabric 1.2.1
		environmentz: EnvironmentZ 1.0.13
		fabric: Fabric API 0.33.1+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-language-scala: Fabric Language Scala 1.0.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabrication: Fabrication 1.3.4
		fabricloader: Fabric Loader 0.11.3
		fabrilousupdater: FabrilousUpdater 1.0.3
		fading: Fading 1.2.3
		fallflyinglib: FallFlyingLib 1.1.0
		fallingleaves: Falling Leaves 1.6.0+1.16.5
		fluidphysics: Fluid Physics 1.4.0+fabric-1.16.4
		full_slabs: Full Slabs 2.0.1
		geckolib3: Geckolib 3.0.30
		hydrogen: Hydrogen 0.2-SNAPSHOT
		io_activej_activej-codegen: activej-codegen 4.1.1
		io_activej_activej-serializer: activej-serializer 4.1.1
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 11
		kibe: Kibe 1.6.7-BETA
		lazydfu: LazyDFU 0.1.2
		lengthyladders: Lengthy Ladders 1.0.1
		libblockattributes_core: LibBlockAttributes (Core) 0.8.7
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.7
		libgui: LibGui 3.3.5+1.16.5
		lightstones: Lightstones 1.3.0
		lithium: Lithium 0.6.4-SNAPSHOT
		loading-timer: Loading Timer 1.4.2-Snapshot
		make-every-biome-spawnable-lol: Make Every Biome Spawnable 1.16.5-1.1.0
		malilib: MaLiLib 0.10.0-dev.21+arne.5
		map_atlases: Map Atlases 1.2.5
		micalibria: Micalibria 1.0.2
		midnight-hats: Midnight Hats 2.0.1
		minecraft: Minecraft 1.16.5
		modifiers: Modifiers 0.1.1
		modmenu: Mod Menu 1.16.9
		more_gems: More Gems 1.1.22
		mostructures: Mo' Structures 1.1.1+mc.1.16.5
		mythicmetals: Mythic Metals 0.9.9
		net_gudenau_lib_unsafe: unsafe 1.4.1
		net_openhft_zero-allocation-hashing: zero-allocation-hashing 0.11
		noplayerlabels: No Player Labels 2.0.1
		notenoughcrashes: Not Enough Crashes 3.2.0
		oldregen: Good Ol' Regen 1.0.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
		org_slf4j_slf4j-api: slf4j-api 1.7.29
		origins: Origins 0.7.0
		playerabilitylib: Pal 1.2.1
		pride: Pride Lib 1.0.0+1.16
		puddles: Puddles 1.0.0
		randompatches: RandomPatches 2.4.5-fabric
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		repurposed_structures: Repurposed Structures 1.16.5-1.10.4-fabric
		retail: Retail 0.2.0
		rocks: This Rocks! 1.3.1
		roughlyenoughitems: Roughly Enough Items 5.11.218
		roughlyenoughitems-api: REI (API) 5.11.218
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.218
		roughlyenoughitems-runtime: REI (Runtime) 5.11.218
		seasons: Fabric Seasons 1.1.1-BETA
		sentimentality2: Sentimentality 2 1.1.0
		sextant: Immersive Travel Overhaul 0.3
		sodium: Sodium 0.1.1+build.330
		spark: spark 1.5.2
		starlight: Starlight fabric-1.0.0-RC2-82ae5ca
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.1
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.1
		throwabletorch: ThrowableTorch 1.16.5
		timecraft: Craft Takes Time 0.4.4
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		trinkets: Trinkets 2.6.7
		tweakeroo: Tweakeroo 0.10.0-dev.20210204.204245
		unearthed: Unearthed 1.1.1
		waystones: Waystones 1.1.1.1
		whereisit: Where Is It 1.11.7
		wi_zoom: WI Zoom 1.3-MC1.16.5
		yungsapi: YUNG's API 1.16.5-Fabric-2
	Player Count: 1 / 8; [class_3222['_K0RR_'/36861, l='ServerLevel[Nowy świat]', x=617.72, y=65.00, z=294.80]]
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
```

**Comment by UltraBlackLinux** [comment]
You should try to give minecraft more ram first

**Comment by K0-RR** [comment]
More than 4GB? It normally doesn't exceed 2,5 GB. I forgot to say this was after some flying in the creative, not just after loading the world.

**Comment by Spottedleaf** [comment]
If you can set the `-XX:+HeapDumpOnOutOfMemoryError` flag in the jvm arguments and give me the heap dump I can take a look. 
You should add me on discord to give it to me - don't put it here, you will publish things you don't want to (namely session id tokens).

**Comment by Spottedleaf** [comment]
Without a heap dump I can't look at this.
