### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by PhanaticD** [Spottedleaf/Starlight#6]
the server crashed whenever the player red_poppy joined, since the only major modification I made to the all of fabric 3 modpack was switch phosphor for starlight i tried reverting that and they were able to join again, which makes me suspect starlight

```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 12/6/20 11:10 AM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at net.minecraft.class_3204.md2eb940$lambda$purge$0$0(class_3204.java:544)
	at net.minecraft.class_4706.removeIf(class_4706.java:535)
	at net.minecraft.class_3204.method_14045(class_3204.java:550)
	at net.minecraft.class_3215.method_12127(class_3215.java:334)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_3204.md2eb940$lambda$purge$0$0(class_3204.java:544)
	at net.minecraft.class_4706.removeIf(class_4706.java:535)
	at net.minecraft.class_3204.method_14045(class_3204.java:550)
	at net.minecraft.class_3215.method_12127(class_3215.java:334)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Red_Poppy'/97889, l='ServerLevel[world]', x=4565.70, y=73.97, z=6502.05]]
	Chunk stats: ServerChunkCache: 1654
	Level dimension: minecraft:the_end
	Derived: true
	Level spawn location: World: (-183,63,110), Chunk: (at 9,3,14 in -12,6; contains blocks -192,0,96 to -177,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 4396463 game time, 6083663 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 165042 (now: false), thunder time: 120499 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Linux (amd64) version 5.4.0-40-generic
	Java Version: 1.8.0_275, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 1762900776 bytes (1681 MB) / 4236247040 bytes (4040 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 16
	JVM Flags: 20 total; -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=100 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Xmx4G -Xms2G
	Fabric Mods: 
		adorn: Adorn 1.12.2+1.16.4
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		advdebug: Advancements Debug 2.2.0
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		appleskin: AppleSkin 1.0.11
		appliedenergistics2: Applied Energistics 2 8.1.0-alpha.13
		architectury: Architectury 1.1.55
		arstheurgia: Ars Theurgia 1.0.5
		artifacts: Artifacts 2.0.2+1.16.4-fabric
		artifice: Artifice 0.13.2+1.16.3
		artofalchemy: Art of Alchemy: Memoriam 1.0.0-rc4+1.16.4
		astromine: Astromine 1.11.4+fabric-1.16.3
		astromine-core: Astromine: Core 1.11.4+fabric-1.16.3
		astromine-discoveries: Astromine: Discoveries 1.11.4+fabric-1.16.3
		astromine-foundations: Astromine: Foundations 1.11.4+fabric-1.16.3
		astromine-technologies: Astromine: Technologies 1.11.4+fabric-1.16.3
		astromine-transportations: Astromine: Transportations 1.11.4+fabric-1.16.3
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bambootweaks: Bamboo Tweaks unspecified
		battletowers: Battle Towers 3.2.1-beta-1.16.4
		bedspreads: Bedspreads 1.3.1-1.16.4
		bettercaves: YUNG's Better Caves 1.16.2-1.0.3
		betterend: Better End 0.7.1-beta
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0
		blade: Blade 2.0.0
		blast: BLAST 1.4
		blockshifter: Blockshifter 1.3.2+fabric-1.16.4
		blockus: Blockus 1.6.8+1.16.4
		blue_endless_jankson: jankson +
		byg: BYG 1.1.3
		campanion: Campanion 1.2.0+build.39
		cardinal-components: Cardinal Components API 2.7.9
		cardinal-components-base: Cardinal Components API (base) 2.7.9
		cardinal-components-block: Cardinal Components API (blocks) 2.7.9
		cardinal-components-chunk: Cardinal Components API (chunks) 2.7.9
		cardinal-components-entity: Cardinal Components API (entities) 2.7.9
		cardinal-components-item: Cardinal Components API (items) 2.7.9
		cardinal-components-level: Cardinal Components API (world saves) 2.7.9
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.7.9
		cardinal-components-util: Cardinal Components API (utilities) 2.7.9
		cardinal-components-world: Cardinal Components API (worlds) 2.7.9
		carrier: Carrier 1.6.1
		cavebiomes: Cave Biomes 0.5.1
		chainmail: Chainmail 0.5.0
		charm: Charm 2.1.4
		charmonium: Charmonium 2.1.4
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cinderscapes: Cinderscapes 1.2.4+build.43-1.16.4
		cleancut: CleanCut mc1.16-2.1-fabric
		cloth-api: Cloth API 1.4.9
		cloth-armor-api-v1: Cloth Armor API v1 1.4.9
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.9
		cloth-common-events-v1: Cloth Common Events v1 1.4.9
		cloth-config2: Cloth Config v4 4.8.3
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.9
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
		cloth-utils-v1: Cloth Utils v1 1.4.9
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_github_nathanpb_safer: Safer 1.1.0
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		compressedblocks: Compressed Blocks 1.0
		computercraft: CC:T for Fabric 1.91.2
		controlling: Controlling For Fabric 1.1.2
		couplings: Couplings 1.3.1
		crookedcrooks: Crooked Crooks 1.3.2+1.16.4
		croptopia: Croptopia 1.0.5-1.16.3-FABRIC
		crusade: Crusade 1.1.4+1.16.2
		dankstorage: Dank Storage 1.9a-1.16.3
		darkpaintings: Dark Paintings 1.0.0
		dawn: Dawn API 1.5.4
		decimal_coins: Decimal Coins 1.16.2-1.2.0
		diggusmaximus: Diggus Maximus 1.4.2-1.16.3
		dml-refabricated: Deep Mob Learning: Refabricated 0.3.1-beta5
		dwarfcoal: Dwarf Coal 1.16.2-1.0.0
		eggtab: Egg Tab 1.3.2+1.16-fabric
		expandedstorage: ExpandedStorage 5.6.31
		ezpas: Ezpas 1.2.3-1.16.2
		fabric: Fabric API 0.27.1+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
		fabric-furnaces: Fabric Furnaces 1.3.2-1.16.2
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
		fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
		fabric-language-scala: Fabric Language Scala 0.3.2.12
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+6a2618f53a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f4e
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.1+285766753a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.2+1944f3e03a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.1+f1d8af063a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.10.8
		fabrikommander: FabriKommander 1.0.0-MC1.16.3
		fallflyinglib: FallFlyingLib 1.1.0
		fatxporbs: Fat Experience Orbs 0.0.9
		fermion: Fermion 2.1.191
		fermion-modkeys: Fermion Modifier Keys 1.8.180-snapshot
		fiber: fiber 0.23.0-2
		flamingo_ooo: Flamingo, oh, oh, oh... 1.0.4-MC1.16.3-fabric
		flan: Flan 1.16.2-1.2.0
		flonters: Flonters 1.1.1+1.16.2
		flora-doubling: Flora Doubling 1.3.0+1.16.4-fabric
		gameinfo: GameInfo 2.0.0a-experimental-06.1 1.16.2
		gateofbabylon: Gate Of Babylon 1.1.2-1.16.2
		geckolib: Geckolib 2.0.0
		givemehats: Give Me Hats! 1.3
		glassdoor: Glass Doors 1.5.0-1.16
		glassential: Glassential 1.16.1-1.1.4
		goml: Get Off My Lawn 1.2.2-beta
		hard-hat-steve: Hard Hat Steve 1.2.0
		harvest: Harvest 1.2.12
		harvest_scythes: Harvest Scythes 1.0.4
		hctm-base: HCTM Base 3.4.0
		horseinfo: Horse Info 0.2.2-1.16.1
		ignis-fatuus: Ignis Fatuus 1.1.0
		improved-stations: Improved Stations 2.0.3
		indrev: Industrial Revolution 1.7.15-BETA
		inmis: Inmis 2.0.0-beta-1.16.2
		inventorysorter: Inventory Sorter 1.7.4-1.16
		iron-jetpacks: Iron Jetpacks 0.2.5
		jankson: Jankson 3.0.1+j1.2.0
		javax_vecmath_vecmath: vecmath 1.5.2
		jumploader: Jumploader 2.1.0
		kibe: Kibe 1.5.2-BETA
		ktdatataglib: KtDataTagLib 1.4.0
		kubejs: KubeJS 1.5.5
		kyrptconfig: Kytpt Config 1.1.6-1.16
		lapisreserve: Lapis Reserve 1.0.6
		libblockattributes: LibBlockAttributes 0.8.4
		libblockattributes_core: LibBlockAttributes (Core) 0.8.4
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.4
		libblockattributes_items: LibBlockAttributes (Items) 0.8.4
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.2.2+1.16.3
		library_of_exile: Library of Exile 1.0.6
		libstructure: LibStructure 1.5
		lithium: Lithium 0.6.0
		lithium-api: Lithium API 0.6.0
		magna: Magna 1.4.3-1.16.2
		mcdict: MCDict 2.0.0+1.16.4
		megane: megane 3.0.7+1.16.4
		megane-api: megane-api 3.0.7+1.16.4
		megane-impl: megane-impl 3.0.7+1.16.4
		megane-runtime: megane-runtime 3.0.7+1.16.4
		minecraft: Minecraft 1.16.4
		mm: Manningham Mills 2.1
		mo_glass: Mo Glass 1.5-MC1.16.4
		modern_industrialization: Modern Industrialization 0.3.9
		mostructures: Mo' Structures 1.0.1+mc.1.16.4
		netherite_plus: Netherite Plus Mod 1.1.0
		nourish: Nourish 1.1.1
		org_codehaus_groovy_groovy: groovy 3.0.3
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
		org_joml_joml: joml 1.9.25
		org_yaml_snakeyaml: snakeyaml 1.25
		packages: Packages 1.1.1
		patchouli: Patchouli 1.16.4-48-FABRIC
		phonos: Phonos 0.1.0-beta
		piglib: Piglib 1.0.1
		playerabilitylib: Pal 1.2.1
		polymorph: Polymorph 0.0.5-1.16.3
		qcommon-cfg-core: qcommon-cfg-core 3.2.0
		qcommon-croco: Croco 2.1.1
		quickshulker: Quick Shulker 1.1.11-1.16
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		reborncore: Reborn Core 4.6.1+build.97
		repurposed_structures: Repurposed Structures 1.16.4-1.7.3
		respawnablepets: Respawnable Pets 1.16.4-1
		roughlyenoughitems: Roughly Enough Items 5.8.7
		roughlyenoughitems-api: REI (API) 5.8.7
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.7
		roughlyenoughitems-runtime: REI (Runtime) 5.8.7
		rswires: RSWires 4.9.1
		rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
		secretrooms: Secret Rooms 0.9.2+1.16.2
		shapes: Shapes 2.0.0+build.10
		shulkerboxtooltip: Shulker Box Tooltip 2.3.3+1.16.4
		simpleteleporters: Simple Teleporters 2.2.1
		simplexterrain: Simplex Terrain 0.7.1
		smootherbedrock: Smoother Bedrock 1.0.0
		spark: spark 1.4.3
		staffofbuilding: Staff of Building 1.2.3-1.16.2
		starlight: Starlight 0.0.1-SNAPSHOT
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stonecutter-tweaks: Stonecutter Tweaks 1.1.0-1.16
		strawdummy: Straw Dummy 1.4.0
		structure-helpers: Structure Helpers 3.0.0
		survivalisland: Survival Island 0.1.5
		tacocraft: TacoCraft 1.3.1+mc.1.16
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 3.7.1+build.162
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.0+build.1
		terraform-config-api-v1: Terraform Config API (v1) 1.0.0+build.1
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.0.0+build.1
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.0+build.1
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.0+build.3
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.0+build.1
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.1+build.3
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.0+build.1
		terrestria: Terrestria 2.1.5+build.28
		tis3d: TIS-3D 1.6.0
		tis3d-additions: TIS-3D Additions 0.2.1+1.16.2
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		totemmod: Wither Totems Mod 0.3.2
		trapexpansion: Trap Expansion 1.3.2
		traverse: Traverse 3.0.3+build.13
		trinkets: Trinkets 2.6.7
		truerooms: True Secret Rooms 1.0.3
		vanilla-hammers: Vanilla Hammers 3.0.1-1.16.3
		vanilladeathchest: VanillaDeathChest 1.16.3-1.11.0.7-fabric
		vanillaexcavators: Vanilla Excavators 1.1.0
		villagerhats: Villager Hats fabric-1.16.4-1.0.1
		voyager: Voyager 1.0.0
		waila: Hwyla 1.9.22
		waystones: Waystones 1.0.10
		wild_explorer: Wild Explorer 1.2.1
		winged: Winged Mod 1.16.2-1.4.1
		wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
		woodenhoppers: Wooden Hoppers 1.0.0
		woods_and_mires: Woods and Mires 1.0.3+1.16.3
		wrenchable: Wrenchable 1.0.0+1.16.1
		xaerominimap: Xaero's Minimap 20.28.1
		xaeroworldmap: Xaero's World Map 1.11.3
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.16.4-Fabric-1
	Player Count: 4 / 20; [class_3222['Whiist'/25275, l='ServerLevel[world]', x=47.57, y=77.00, z=2545.37], class_3222['_Gryz_'/68616, l='ServerLevel[world]', x=171.12, y=176.12, z=-6069.06], class_3222['Eveybean'/84690, l='ServerLevel[world]', x=-754.14, y=62.67, z=-921.09], class_3222['Red_Poppy'/97889, l='ServerLevel[world]', x=4565.70, y=73.97, z=6502.05]]
	Data Packs: vanilla (incompatible), fabric/adorn, fabric/appliedenergistics2, fabric/arstheurgia, fabric/artifacts, fabric/artofalchemy, fabric/astromine-core, fabric/astromine-discoveries, fabric/astromine-foundations, fabric/astromine-technologies, fabric/astromine-transportations, fabric/bambootweaks, fabric/battletowers, fabric/bedspreads, fabric/betterend, fabric/blast, fabric/blockshifter, fabric/blockus, fabric/byg, fabric/campanion, fabric/carrier, fabric/cavebiomes, fabric/charm (incompatible), fabric/cinderscapes, fabric/compressedblocks, fabric/computercraft (incompatible), fabric/crookedcrooks, fabric/croptopia, fabric/crusade, fabric/dankstorage, fabric/decimal_coins (incompatible), fabric/dml-refabricated, fabric/dwarfcoal, fabric/expandedstorage, fabric/ezpas, fabric/fabric-furnaces, fabric/fabric-tool-attribute-api-v1, fabric/flamingo_ooo, fabric/flonters, fabric/flora-doubling, fabric/gateofbabylon, fabric/glassdoor, fabric/glassential, fabric/goml, fabric/hard-hat-steve (incompatible), fabric/harvest, fabric/hctm-base, fabric/ignis-fatuus, fabric/improved-stations, fabric/indrev, fabric/inmis, fabric/iron-jetpacks (incompatible), fabric/kibe, fabric/kubejs (incompatible), fabric/libcd, fabric/mo_glass, fabric/modern_industrialization, fabric/mostructures, fabric/netherite_plus, fabric/nourish, fabric/packages, fabric/phonos, fabric/piglib, fabric/repurposed_structures, fabric/respawnablepets, fabric/rswires, fabric/secretrooms, fabric/simpleteleporters, fabric/staffofbuilding, fabric/strawdummy, fabric/structure-helpers, fabric/tacocraft, fabric/techreborn, fabric/terrestria, fabric/tis3d (incompatible), fabric/tis3d-additions, fabric/totemmod, fabric/trapexpansion, fabric/traverse, fabric/trinkets, fabric/truerooms, fabric/vanilla-hammers, fabric/vanillaexcavators, fabric/villagerhats, fabric/waystones, fabric/wild_explorer, fabric/winged, fabric/wolveswitharmor, fabric/woodenhoppers, fabric/woods_and_mires, phonos:data_pack, secretrooms:server_pack
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by Spottedleaf** [comment]
This looks unrelated, but I'm willing to bet once again other mods are calling things like setBlockState async which could run some of my logic which is not safe to run off-main. I'll rewrite the block change handling to be like tuinity, where it defends against this.
